# Generated by Django 4.0.5 on 2022-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_select', models.CharField(max_length=80)),
                ('section_select2', models.CharField(max_length=80)),
                ('section_select3', models.CharField(max_length=80)),
                ('section_menu', models.CharField(max_length=100)),
                ('section_menu2', models.CharField(max_length=100)),
                ('section_menu3', models.CharField(max_length=100)),
                ('section_menu4', models.CharField(max_length=100)),
                ('section_menu5', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=30)),
            ],
        ),
    ]
