# Generated by Django 4.0.5 on 2022-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=60)),
                ('likes', models.IntegerField()),
                ('view', models.IntegerField()),
            ],
        ),
    ]
