# Generated by Django 4.0.5 on 2022-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('upload_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('short_inf', models.CharField(max_length=150)),
                ('blog_name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
            ],
        ),
    ]
