# Generated by Django 4.0.5 on 2022-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
    ]
